<?php

namespace Tom32i\PortfolioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
	public function findAllOrdered()
	{
		return $this->getEntityManager()
            ->createQuery('SELECT p FROM Tom32iPortfolioBundle:Project p ORDER BY p.released DESC')
            ->getResult();
	}
}
